alias adbcap="adb shell screencap -p"
alias tmux="TERM=screen-256color tmux -2"
alias vi="vim"
alias mux="TERM=screen-256color tmuxinator"
alias cp="cp -i"
alias df="df -h"
alias grep="grep --color=auto"
alias ag="ag -i"
alias mkdir="mkdir -p"
